theme: jekyll-theme-minimal
plugins:
  - jekyll-optional-front-matter
description: >
  This project deploys a data dump annotating IIIF images of printed books from the 16th century regarding the reuse of their woodcut illustrations. 
  This is a supplement to: Computergestützte Analyse von Illustrationswiederverwendungen in deutschsprachigen Drucken des 16. Jahrhunderts. Am Beispiel Frankfurt am Main. 

